#!/usr/bin/env bash

# Runs at the end of git flow release start
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)
# $4    The base from which this release is started
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
# @see https://github.com/petervanderdoes/gitflow-avh/blob/develop/hooks/post-flow-release-start
VERSION=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

# Find the folder location through potential symlinks
if [[ -z $HOOKS_DIR ]]; then
  HOOKS_DIR="$0"
  while [[ -h $HOOKS_DIR ]]; do HOOK_PATH=$(readlink "$HOOKS_DIR"); done
  HOOKS_DIR=$(dirname $HOOKS_DIR)
fi
source "$HOOKS_DIR"/functions.sh
source "$HOOKS_DIR"/functions-lang.sh

if get_config_bool gitflow.branch.bump-chart true; then
  CHART_DIR=$(get_config gitflow.path.chart "$ROOT_DIR/chart")
  if [[ -f $CHART_DIR/Chart.yaml ]]; then
    git stash pop --quiet
    git add "$CHART_DIR/Chart.yaml"
    die_on_error "Failed to stage $CHART_DIR/Chart.yaml"
    CHART_VERSION=$(get_chart_version "$CHART_DIR/Chart.yaml")
    git commit -m "Bumped Chart to version $CHART_VERSION" "$CHART_DIR/Chart.yaml"
    die_on_error "Failed to commit new Chart version $CHART_VERSION"
  fi
fi

VERSION_FILE=$(find_version_file)
die_on_error "$VERSION_FILE"

VERSION=$(normalize_version "$VERSION")

update_version_file "$VERSION_FILE" $VERSION
die_on_error "Failed to update $VERSION_FILE with version $VERSION"

if get_config_bool gitflow.branch.bump-dockerfile true; then
  if [[ -f $ROOT_DIR/Dockerfile ]]; then
    update_dockerfile_version "$ROOT_DIR/Dockerfile" $VERSION
    die_on_error "Failed to update Dockerfile with version $VERSION"
    git add Dockerfile
    die_on_error "Failed to stage Dockerfile"
  fi
fi

git add "$VERSION_FILE"
die_on_error "Failed to stage $VERSION_FILE"
git commit -m "Bumped to version $VERSION"
die_on_error "Failed to commit new version $VERSION"

exit 0
