#!/usr/bin/env bash

if [[ -z $HOOKS_DIR ]]; then
  HOOKS_DIR="$0"
  while [[ -h $HOOKS_DIR ]]; do HOOK_PATH=$(readlink "$HOOKS_DIR"); done
  HOOKS_DIR=$(dirname $HOOKS_DIR)
fi
source "$HOOKS_DIR"/functions.sh
[[ -f "$HOOKS_DIR"/functions-lang.sh ]] && source "$HOOKS_DIR"/functions-lang.sh

verbose "Hook: pre-commit"

if ! get_config_bool gitflow.allow-master-commit; then
  MASTER=$(git config --get gitflow.branch.master)
  BRANCH=$(git symbolic-ref HEAD)
  [[ $BRANCH == "refs/heads/$MASTER" ]] && die "Direct commits to the $MASTER branch are forbidden"
fi

# Check if there is any merge that is not resolved in the files to commit
if ! get_config_bool gitflow.allow-conflict-commit; then
  files_to_merge=()
  for file in $(git diff-index --name-only --diff-filter=ACM --cached HEAD --); do
    if grep -Erls "^<<<<<<< |^>>>>>>> $" "$file" 2>&1 >/dev/null; then
      if ! is_binary "$file"; then
        files_to_merge=($files_to_merge $file)
      fi
    fi
  done
  [[ ${#files_to_merge[@]} > 0 ]] && die "Resolve these merges before committing! ${files_to_merge[@]}"
fi

if get_config_bool gitflow.prettify true; then
  if declare -F prettify_staged_files &>/dev/null; then
    prettify_staged_files
    die_on_error "$ERROR \nFix the formatting errors and try again"
  fi
fi

if get_config_bool gitflow.must-pass-lint true; then
  if declare -F lint_staged_files &>/dev/null; then
    lint_staged_files
    die_on_error "$ERROR \nFix the lint errors and try again"
  fi
fi

exit 0
